version = 1
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
SPDX-PackageName = "kleopatra"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/kleopatra"

[[annotations]]
path = ["README.packagers", "tests/gpg-connect-agent-scripts/**", "tests/gnupg_home/**", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["src/kwatchgnupg/images/*"]
precedence = "override"
SPDX-FileCopyrightText = [ "Breeze Icons contributors", "g10 Code GmbH" ]
SPDX-FileContributor = "Carl Schwan <carl.schwan@gnupg.com>"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = ["src/icons/macos/*"]
precedence = "override"
SPDX-FileCopyrightText = "Breeze Icons contributors"
SPDX-License-Identifier = "LGPL-3.0-or-later"
